[package]
description = "Data structures shared between the client and server."
name = "thetis-common"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
serde = "1.0.77"
serde_derive = "1.0.77"
